// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_types/definitions/rerun/blueprint/archetypes/transform_3d_arrows_blueprint.fbs".

#include "transform3d_arrows_blueprint.hpp"

#include "../../collection_adapter_builtins.hpp"

namespace rerun::blueprint::archetypes {
    Transform3dArrowsBlueprint Transform3dArrowsBlueprint::clear_fields() {
        auto archetype = Transform3dArrowsBlueprint();
        archetype.transform_is_pinhole =
            ComponentBatch::empty<rerun::blueprint::components::Visible>(
                Descriptor_transform_is_pinhole
            )
                .value_or_throw();
        archetype.transform_has_axis_length =
            ComponentBatch::empty<rerun::blueprint::components::Visible>(
                Descriptor_transform_has_axis_length
            )
                .value_or_throw();
        archetype.transform_is_alone = ComponentBatch::empty<rerun::blueprint::components::Visible>(
                                           Descriptor_transform_is_alone
        )
                                           .value_or_throw();
        archetype.transform_exists =
            ComponentBatch::empty<rerun::blueprint::components::Visible>(Descriptor_transform_exists
            )
                .value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> Transform3dArrowsBlueprint::columns(
        const Collection<uint32_t>& lengths_
    ) {
        std::vector<ComponentColumn> columns;
        columns.reserve(5);
        if (transform_is_pinhole.has_value()) {
            columns.push_back(transform_is_pinhole.value().partitioned(lengths_).value_or_throw());
        }
        if (transform_has_axis_length.has_value()) {
            columns.push_back(
                transform_has_axis_length.value().partitioned(lengths_).value_or_throw()
            );
        }
        if (transform_is_alone.has_value()) {
            columns.push_back(transform_is_alone.value().partitioned(lengths_).value_or_throw());
        }
        if (transform_exists.has_value()) {
            columns.push_back(transform_exists.value().partitioned(lengths_).value_or_throw());
        }
        columns.push_back(ComponentColumn::from_indicators<Transform3dArrowsBlueprint>(
                              static_cast<uint32_t>(lengths_.size())
        )
                              .value_or_throw());
        return columns;
    }

    Collection<ComponentColumn> Transform3dArrowsBlueprint::columns() {
        if (transform_is_pinhole.has_value()) {
            return columns(std::vector<uint32_t>(transform_is_pinhole.value().length(), 1));
        }
        if (transform_has_axis_length.has_value()) {
            return columns(std::vector<uint32_t>(transform_has_axis_length.value().length(), 1));
        }
        if (transform_is_alone.has_value()) {
            return columns(std::vector<uint32_t>(transform_is_alone.value().length(), 1));
        }
        if (transform_exists.has_value()) {
            return columns(std::vector<uint32_t>(transform_exists.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::blueprint::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>>
        AsComponents<blueprint::archetypes::Transform3dArrowsBlueprint>::as_batches(
            const blueprint::archetypes::Transform3dArrowsBlueprint& archetype
        ) {
        using namespace blueprint::archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(5);

        if (archetype.transform_is_pinhole.has_value()) {
            cells.push_back(archetype.transform_is_pinhole.value());
        }
        if (archetype.transform_has_axis_length.has_value()) {
            cells.push_back(archetype.transform_has_axis_length.value());
        }
        if (archetype.transform_is_alone.has_value()) {
            cells.push_back(archetype.transform_is_alone.value());
        }
        if (archetype.transform_exists.has_value()) {
            cells.push_back(archetype.transform_exists.value());
        }
        {
            auto result = ComponentBatch::from_indicator<Transform3dArrowsBlueprint>();
            RR_RETURN_NOT_OK(result.error);
            cells.emplace_back(std::move(result.value));
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
