// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_types/definitions/rerun/blueprint/archetypes/transform_3d_arrows_blueprint.fbs".

#pragma once

#include "../../blueprint/components/visible.hpp"
#include "../../collection.hpp"
#include "../../component_batch.hpp"
#include "../../component_column.hpp"
#include "../../indicator_component.hpp"
#include "../../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace rerun::blueprint::archetypes {
    /// **Archetype**: Configuration for when to visualize Transform3DArrows
    struct Transform3dArrowsBlueprint {
        /// Show arrows if there is a PinHole camera entity in the path
        std::optional<ComponentBatch> transform_is_pinhole;

        /// Show arrows if axis length is specified
        std::optional<ComponentBatch> transform_has_axis_length;

        /// Shows arrows if the Transform3D is the only entity on that entity path
        std::optional<ComponentBatch> transform_is_alone;

        /// Always show arrows
        std::optional<ComponentBatch> transform_exists;

      public:
        static constexpr const char IndicatorComponentName[] =
            "rerun.blueprint.components.Transform3dArrowsBlueprintIndicator";

        /// Indicator component, used to identify the archetype when converting to a list of components.
        using IndicatorComponent = rerun::components::IndicatorComponent<IndicatorComponentName>;
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] =
            "rerun.blueprint.archetypes.Transform3dArrowsBlueprint";

        /// `ComponentDescriptor` for the `transform_is_pinhole` field.
        static constexpr auto Descriptor_transform_is_pinhole = ComponentDescriptor(
            ArchetypeName, "transform_is_pinhole",
            Loggable<rerun::blueprint::components::Visible>::Descriptor.component_name
        );
        /// `ComponentDescriptor` for the `transform_has_axis_length` field.
        static constexpr auto Descriptor_transform_has_axis_length = ComponentDescriptor(
            ArchetypeName, "transform_has_axis_length",
            Loggable<rerun::blueprint::components::Visible>::Descriptor.component_name
        );
        /// `ComponentDescriptor` for the `transform_is_alone` field.
        static constexpr auto Descriptor_transform_is_alone = ComponentDescriptor(
            ArchetypeName, "transform_is_alone",
            Loggable<rerun::blueprint::components::Visible>::Descriptor.component_name
        );
        /// `ComponentDescriptor` for the `transform_exists` field.
        static constexpr auto Descriptor_transform_exists = ComponentDescriptor(
            ArchetypeName, "transform_exists",
            Loggable<rerun::blueprint::components::Visible>::Descriptor.component_name
        );

      public:
        Transform3dArrowsBlueprint() = default;
        Transform3dArrowsBlueprint(Transform3dArrowsBlueprint&& other) = default;
        Transform3dArrowsBlueprint(const Transform3dArrowsBlueprint& other) = default;
        Transform3dArrowsBlueprint& operator=(const Transform3dArrowsBlueprint& other) = default;
        Transform3dArrowsBlueprint& operator=(Transform3dArrowsBlueprint&& other) = default;

        /// Update only some specific fields of a `Transform3dArrowsBlueprint`.
        static Transform3dArrowsBlueprint update_fields() {
            return Transform3dArrowsBlueprint();
        }

        /// Clear all the fields of a `Transform3dArrowsBlueprint`.
        static Transform3dArrowsBlueprint clear_fields();

        /// Show arrows if there is a PinHole camera entity in the path
        Transform3dArrowsBlueprint with_transform_is_pinhole(
            const rerun::blueprint::components::Visible& _transform_is_pinhole
        ) && {
            transform_is_pinhole = ComponentBatch::from_loggable(
                                       _transform_is_pinhole,
                                       Descriptor_transform_is_pinhole
            )
                                       .value_or_throw();
            return std::move(*this);
        }

        /// Show arrows if axis length is specified
        Transform3dArrowsBlueprint with_transform_has_axis_length(
            const rerun::blueprint::components::Visible& _transform_has_axis_length
        ) && {
            transform_has_axis_length = ComponentBatch::from_loggable(
                                            _transform_has_axis_length,
                                            Descriptor_transform_has_axis_length
            )
                                            .value_or_throw();
            return std::move(*this);
        }

        /// Shows arrows if the Transform3D is the only entity on that entity path
        Transform3dArrowsBlueprint with_transform_is_alone(
            const rerun::blueprint::components::Visible& _transform_is_alone
        ) && {
            transform_is_alone =
                ComponentBatch::from_loggable(_transform_is_alone, Descriptor_transform_is_alone)
                    .value_or_throw();
            return std::move(*this);
        }

        /// Always show arrows
        Transform3dArrowsBlueprint with_transform_exists(
            const rerun::blueprint::components::Visible& _transform_exists
        ) && {
            transform_exists =
                ComponentBatch::from_loggable(_transform_exists, Descriptor_transform_exists)
                    .value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace rerun::blueprint::archetypes

namespace rerun {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<blueprint::archetypes::Transform3dArrowsBlueprint> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(
            const blueprint::archetypes::Transform3dArrowsBlueprint& archetype
        );
    };
} // namespace rerun
