# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_types/definitions/rerun/blueprint/archetypes/transform_3d_arrows_blueprint.fbs".

# You can extend this class by creating a "Transform3dArrowsBlueprintExt" class in "transform3d_arrows_blueprint_ext.py".

from __future__ import annotations

from typing import Any

from attrs import define, field

from ... import datatypes
from ..._baseclasses import (
    Archetype,
)
from ...blueprint import components as blueprint_components
from ...error_utils import catch_and_log_exceptions

__all__ = ["Transform3dArrowsBlueprint"]


@define(str=False, repr=False, init=False)
class Transform3dArrowsBlueprint(Archetype):
    """**Archetype**: Configuration for when to visualize Transform3DArrows."""

    def __init__(
        self: Any,
        *,
        transform_is_pinhole: datatypes.BoolLike | None = None,
        transform_has_axis_length: datatypes.BoolLike | None = None,
        transform_is_alone: datatypes.BoolLike | None = None,
        transform_exists: datatypes.BoolLike | None = None,
    ):
        """
        Create a new instance of the Transform3dArrowsBlueprint archetype.

        Parameters
        ----------
        transform_is_pinhole:
            Show arrows if there is a PinHole camera entity in the path
        transform_has_axis_length:
            Show arrows if axis length is specified
        transform_is_alone:
            Shows arrows if the Transform3D is the only entity on that entity path
        transform_exists:
            Always show arrows

        """

        # You can define your own __init__ function as a member of Transform3dArrowsBlueprintExt in transform3d_arrows_blueprint_ext.py
        with catch_and_log_exceptions(context=self.__class__.__name__):
            self.__attrs_init__(
                transform_is_pinhole=transform_is_pinhole,
                transform_has_axis_length=transform_has_axis_length,
                transform_is_alone=transform_is_alone,
                transform_exists=transform_exists,
            )
            return
        self.__attrs_clear__()

    def __attrs_clear__(self) -> None:
        """Convenience method for calling `__attrs_init__` with all `None`s."""
        self.__attrs_init__(
            transform_is_pinhole=None,
            transform_has_axis_length=None,
            transform_is_alone=None,
            transform_exists=None,
        )

    @classmethod
    def _clear(cls) -> Transform3dArrowsBlueprint:
        """Produce an empty Transform3dArrowsBlueprint, bypassing `__init__`."""
        inst = cls.__new__(cls)
        inst.__attrs_clear__()
        return inst

    @classmethod
    def from_fields(
        cls,
        *,
        clear_unset: bool = False,
        transform_is_pinhole: datatypes.BoolLike | None = None,
        transform_has_axis_length: datatypes.BoolLike | None = None,
        transform_is_alone: datatypes.BoolLike | None = None,
        transform_exists: datatypes.BoolLike | None = None,
    ) -> Transform3dArrowsBlueprint:
        """
        Update only some specific fields of a `Transform3dArrowsBlueprint`.

        Parameters
        ----------
        clear_unset:
            If true, all unspecified fields will be explicitly cleared.
        transform_is_pinhole:
            Show arrows if there is a PinHole camera entity in the path
        transform_has_axis_length:
            Show arrows if axis length is specified
        transform_is_alone:
            Shows arrows if the Transform3D is the only entity on that entity path
        transform_exists:
            Always show arrows

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            kwargs = {
                "transform_is_pinhole": transform_is_pinhole,
                "transform_has_axis_length": transform_has_axis_length,
                "transform_is_alone": transform_is_alone,
                "transform_exists": transform_exists,
            }

            if clear_unset:
                kwargs = {k: v if v is not None else [] for k, v in kwargs.items()}  # type: ignore[misc]

            inst.__attrs_init__(**kwargs)
            return inst

        inst.__attrs_clear__()
        return inst

    @classmethod
    def cleared(cls) -> Transform3dArrowsBlueprint:
        """Clear all the fields of a `Transform3dArrowsBlueprint`."""
        return cls.from_fields(clear_unset=True)

    transform_is_pinhole: blueprint_components.VisibleBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=blueprint_components.VisibleBatch._converter,  # type: ignore[misc]
    )
    # Show arrows if there is a PinHole camera entity in the path
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    transform_has_axis_length: blueprint_components.VisibleBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=blueprint_components.VisibleBatch._converter,  # type: ignore[misc]
    )
    # Show arrows if axis length is specified
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    transform_is_alone: blueprint_components.VisibleBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=blueprint_components.VisibleBatch._converter,  # type: ignore[misc]
    )
    # Shows arrows if the Transform3D is the only entity on that entity path
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    transform_exists: blueprint_components.VisibleBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=blueprint_components.VisibleBatch._converter,  # type: ignore[misc]
    )
    # Always show arrows
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    __str__ = Archetype.__str__
    __repr__ = Archetype.__repr__  # type: ignore[assignment]
