// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_types/definitions/rerun/blueprint/archetypes/transform_3d_arrows_blueprint.fbs".

#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]

use ::re_types_core::try_serialize_field;
use ::re_types_core::SerializationResult;
use ::re_types_core::{ComponentBatch, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentName};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: Configuration for when to visualize Transform3DArrows
#[derive(Clone, Debug, Default)]
pub struct Transform3dArrowsBlueprint {
    /// Show arrows if there is a PinHole camera entity in the path
    pub transform_is_pinhole: Option<SerializedComponentBatch>,

    /// Show arrows if axis length is specified
    pub transform_has_axis_length: Option<SerializedComponentBatch>,

    /// Shows arrows if the Transform3D is the only entity on that entity path
    pub transform_is_alone: Option<SerializedComponentBatch>,

    /// Always show arrows
    pub transform_exists: Option<SerializedComponentBatch>,
}

impl Transform3dArrowsBlueprint {
    /// Returns the [`ComponentDescriptor`] for [`Self::transform_is_pinhole`].
    #[inline]
    pub fn descriptor_transform_is_pinhole() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype_name: Some("rerun.blueprint.archetypes.Transform3dArrowsBlueprint".into()),
            component_name: "rerun.blueprint.components.Visible".into(),
            archetype_field_name: Some("transform_is_pinhole".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::transform_has_axis_length`].
    #[inline]
    pub fn descriptor_transform_has_axis_length() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype_name: Some("rerun.blueprint.archetypes.Transform3dArrowsBlueprint".into()),
            component_name: "rerun.blueprint.components.Visible".into(),
            archetype_field_name: Some("transform_has_axis_length".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::transform_is_alone`].
    #[inline]
    pub fn descriptor_transform_is_alone() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype_name: Some("rerun.blueprint.archetypes.Transform3dArrowsBlueprint".into()),
            component_name: "rerun.blueprint.components.Visible".into(),
            archetype_field_name: Some("transform_is_alone".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::transform_exists`].
    #[inline]
    pub fn descriptor_transform_exists() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype_name: Some("rerun.blueprint.archetypes.Transform3dArrowsBlueprint".into()),
            component_name: "rerun.blueprint.components.Visible".into(),
            archetype_field_name: Some("transform_exists".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for the associated indicator component.
    #[inline]
    pub fn descriptor_indicator() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype_name: Some("rerun.blueprint.archetypes.Transform3dArrowsBlueprint".into()),
            component_name: "rerun.blueprint.components.Transform3dArrowsBlueprintIndicator".into(),
            archetype_field_name: None,
        }
    }
}

static REQUIRED_COMPONENTS: once_cell::sync::Lazy<[ComponentDescriptor; 0usize]> =
    once_cell::sync::Lazy::new(|| []);

static RECOMMENDED_COMPONENTS: once_cell::sync::Lazy<[ComponentDescriptor; 1usize]> =
    once_cell::sync::Lazy::new(|| [Transform3dArrowsBlueprint::descriptor_indicator()]);

static OPTIONAL_COMPONENTS: once_cell::sync::Lazy<[ComponentDescriptor; 4usize]> =
    once_cell::sync::Lazy::new(|| {
        [
            Transform3dArrowsBlueprint::descriptor_transform_is_pinhole(),
            Transform3dArrowsBlueprint::descriptor_transform_has_axis_length(),
            Transform3dArrowsBlueprint::descriptor_transform_is_alone(),
            Transform3dArrowsBlueprint::descriptor_transform_exists(),
        ]
    });

static ALL_COMPONENTS: once_cell::sync::Lazy<[ComponentDescriptor; 5usize]> =
    once_cell::sync::Lazy::new(|| {
        [
            Transform3dArrowsBlueprint::descriptor_indicator(),
            Transform3dArrowsBlueprint::descriptor_transform_is_pinhole(),
            Transform3dArrowsBlueprint::descriptor_transform_has_axis_length(),
            Transform3dArrowsBlueprint::descriptor_transform_is_alone(),
            Transform3dArrowsBlueprint::descriptor_transform_exists(),
        ]
    });

impl Transform3dArrowsBlueprint {
    /// The total number of components in the archetype: 0 required, 1 recommended, 4 optional
    pub const NUM_COMPONENTS: usize = 5usize;
}

/// Indicator component for the [`Transform3dArrowsBlueprint`] [`::re_types_core::Archetype`]
pub type Transform3dArrowsBlueprintIndicator =
    ::re_types_core::GenericIndicatorComponent<Transform3dArrowsBlueprint>;

impl ::re_types_core::Archetype for Transform3dArrowsBlueprint {
    type Indicator = Transform3dArrowsBlueprintIndicator;

    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        "rerun.blueprint.archetypes.Transform3dArrowsBlueprint".into()
    }

    #[inline]
    fn display_name() -> &'static str {
        "Transform 3D arrows blueprint"
    }

    #[inline]
    fn indicator() -> SerializedComponentBatch {
        #[allow(clippy::unwrap_used)]
        Transform3dArrowsBlueprintIndicator::DEFAULT
            .serialized()
            .unwrap()
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let transform_is_pinhole = arrays_by_descr
            .get(&Self::descriptor_transform_is_pinhole())
            .map(|array| {
                SerializedComponentBatch::new(
                    array.clone(),
                    Self::descriptor_transform_is_pinhole(),
                )
            });
        let transform_has_axis_length = arrays_by_descr
            .get(&Self::descriptor_transform_has_axis_length())
            .map(|array| {
                SerializedComponentBatch::new(
                    array.clone(),
                    Self::descriptor_transform_has_axis_length(),
                )
            });
        let transform_is_alone = arrays_by_descr
            .get(&Self::descriptor_transform_is_alone())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_transform_is_alone())
            });
        let transform_exists = arrays_by_descr
            .get(&Self::descriptor_transform_exists())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_transform_exists())
            });
        Ok(Self {
            transform_is_pinhole,
            transform_has_axis_length,
            transform_is_alone,
            transform_exists,
        })
    }
}

impl ::re_types_core::AsComponents for Transform3dArrowsBlueprint {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [
            Some(Self::indicator()),
            self.transform_is_pinhole.clone(),
            self.transform_has_axis_length.clone(),
            self.transform_is_alone.clone(),
            self.transform_exists.clone(),
        ]
        .into_iter()
        .flatten()
        .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for Transform3dArrowsBlueprint {}

impl Transform3dArrowsBlueprint {
    /// Create a new `Transform3dArrowsBlueprint`.
    #[inline]
    pub fn new() -> Self {
        Self {
            transform_is_pinhole: None,
            transform_has_axis_length: None,
            transform_is_alone: None,
            transform_exists: None,
        }
    }

    /// Update only some specific fields of a `Transform3dArrowsBlueprint`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `Transform3dArrowsBlueprint`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            transform_is_pinhole: Some(SerializedComponentBatch::new(
                crate::blueprint::components::Visible::arrow_empty(),
                Self::descriptor_transform_is_pinhole(),
            )),
            transform_has_axis_length: Some(SerializedComponentBatch::new(
                crate::blueprint::components::Visible::arrow_empty(),
                Self::descriptor_transform_has_axis_length(),
            )),
            transform_is_alone: Some(SerializedComponentBatch::new(
                crate::blueprint::components::Visible::arrow_empty(),
                Self::descriptor_transform_is_alone(),
            )),
            transform_exists: Some(SerializedComponentBatch::new(
                crate::blueprint::components::Visible::arrow_empty(),
                Self::descriptor_transform_exists(),
            )),
        }
    }

    /// Show arrows if there is a PinHole camera entity in the path
    #[inline]
    pub fn with_transform_is_pinhole(
        mut self,
        transform_is_pinhole: impl Into<crate::blueprint::components::Visible>,
    ) -> Self {
        self.transform_is_pinhole = try_serialize_field(
            Self::descriptor_transform_is_pinhole(),
            [transform_is_pinhole],
        );
        self
    }

    /// Show arrows if axis length is specified
    #[inline]
    pub fn with_transform_has_axis_length(
        mut self,
        transform_has_axis_length: impl Into<crate::blueprint::components::Visible>,
    ) -> Self {
        self.transform_has_axis_length = try_serialize_field(
            Self::descriptor_transform_has_axis_length(),
            [transform_has_axis_length],
        );
        self
    }

    /// Shows arrows if the Transform3D is the only entity on that entity path
    #[inline]
    pub fn with_transform_is_alone(
        mut self,
        transform_is_alone: impl Into<crate::blueprint::components::Visible>,
    ) -> Self {
        self.transform_is_alone =
            try_serialize_field(Self::descriptor_transform_is_alone(), [transform_is_alone]);
        self
    }

    /// Always show arrows
    #[inline]
    pub fn with_transform_exists(
        mut self,
        transform_exists: impl Into<crate::blueprint::components::Visible>,
    ) -> Self {
        self.transform_exists =
            try_serialize_field(Self::descriptor_transform_exists(), [transform_exists]);
        self
    }
}

impl ::re_byte_size::SizeBytes for Transform3dArrowsBlueprint {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.transform_is_pinhole.heap_size_bytes()
            + self.transform_has_axis_length.heap_size_bytes()
            + self.transform_is_alone.heap_size_bytes()
            + self.transform_exists.heap_size_bytes()
    }
}
